Class {
	#name : 'LxxTestSubModule11',
	#superclass : 'LxxTestModule1',
	#category : 'Lcs-PrototypeSystemTests-Support',
	#package : 'Lcs-PrototypeSystemTests',
	#tag : 'Support'
}

{ #category : 'configuration' }
LxxTestSubModule11 class >> defaultModuleName [
	^ 'Prototype 11 Submodule'
]

{ #category : 'as yet unclassified' }
LxxTestSubModule11 class >> owningModules [
	<owningModule: 'LxxTestModule1' priority: 50>
]
