Class {
	#name : #LcsReadOnlyUnitOfWork,
	#superclass : #LcsUnitOfWork,
	#category : #'Lcs-SystemManagement-UnitOfWork'
}

{ #category : #api }
LcsReadOnlyUnitOfWork >> addObject: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> addObject: aDomainObject toCollection: aCollection [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> applyChanges [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> changedSlot: aSlotName valueTo: anObject in: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> deleteObject: aDomainObject [
	"do nothing"
]

{ #category : #api }
LcsReadOnlyUnitOfWork >> setValueIn: aDomainObject slot: aSlotDefiniton to: anObject [ 
	"do nothing"
]
