Class {
	#name : #GtPharoMethodCoderAnnouncementSignal,
	#superclass : #GtPharoExampleSuiteMediatorSignal,
	#instVars : [
		'announcement'
	],
	#category : #'GToolkit-Pharo-Coder-UI-Examples'
}

{ #category : #accessing }
GtPharoMethodCoderAnnouncementSignal >> announcement [
	^ announcement
]

{ #category : #accessing }
GtPharoMethodCoderAnnouncementSignal >> announcement: arg1 [
	announcement := arg1
]
