Class {
	#name : #GtPharoBehaviorNavigationViewModelDeselected,
	#superclass : #Announcement,
	#instVars : [
		'behaviorViewModel'
	],
	#category : #'GToolkit-Pharo-Coder-UI-Navigation - Events'
}

{ #category : #accessing }
GtPharoBehaviorNavigationViewModelDeselected >> behaviorViewModel [
	^ behaviorViewModel
]

{ #category : #accessing }
GtPharoBehaviorNavigationViewModelDeselected >> behaviorViewModel: arg1 [
	behaviorViewModel := arg1
]
