Class {
	#name : #LxxMaleExample,
	#superclass : #LxxGenderExample,
	#category : #'Lcs-PrototypeSystem'
}

{ #category : #defaults }
LxxMaleExample class >> defaultCodeDescription [
	^ 'MaleExample'
]

{ #category : #defaults }
LxxMaleExample class >> defaultCodeName [
	^ 'maleExample'
]

{ #category : #defaults }
LxxMaleExample class >> defaultInstance [
	^ false
]

{ #category : #defaults }
LxxMaleExample class >> defaultShortName [
	^ 'MaleExample'
]
