Class {
	#name : 'LxxPrototype2Submodule',
	#superclass : 'LcsModule',
	#category : 'Lcs-PrototypeSystem-Core',
	#package : 'Lcs-PrototypeSystem',
	#tag : 'Core'
}

{ #category : 'configuration' }
LxxPrototype2Submodule class >> defaultModuleName [
	^ 'Prototype 2 Submodule'
]

{ #category : 'temp' }
LxxPrototype2Submodule class >> owningModules [
	<owningModule: 'LxxPrototype2Module' priority: 50>
]
