Class {
	#name : #LcsSmalltalkConfiguration,
	#superclass : #LcsObject,
	#category : #LcsBase
}

{ #category : #accessing }
LcsSmalltalkConfiguration class >> booleanClass [
	^Boolean
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> dateClass [
	^Date
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> integerClass [
	^Integer
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> objectKeyDictionaryClass [
	^Dictionary
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> setClass [

	^IdentitySet
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> stringClass [
	^String
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> stringDictionaryClass [
	^Dictionary
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> symbolDictionaryClass [

	^Dictionary
]

{ #category : #accessing }
LcsSmalltalkConfiguration class >> timeClass [
	^Time
]
