Class {
	#name : #LcsAddress,
	#superclass : #LcsDomainObject,
	#category : #'Lcs-LegalEntities'
}

{ #category : #accessing }
LcsAddress >> cityName: aString [ 
]

{ #category : #accessing }
LcsAddress >> sate: aString [ 
]

{ #category : #accessing }
LcsAddress >> streetName: aString [ 
]

{ #category : #accessing }
LcsAddress >> streetNumber: anInteger [ 
]

{ #category : #accessing }
LcsAddress >> zipCode: aString [ 
]
