Class {
	#name : 'LcsFemale',
	#superclass : 'LcsGender',
	#category : 'Lcs-LegalEntities-Core',
	#package : 'Lcs-LegalEntities',
	#tag : 'Core'
}

{ #category : 'defaults' }
LcsFemale class >> defaultCode [
	^ 'female'
]

{ #category : 'defaults' }
LcsFemale class >> defaultDescription [
	^ 'Female'
]

{ #category : 'defaults' }
LcsFemale class >> defaultInstance [
	^ false
]

{ #category : 'defaults' }
LcsFemale class >> defaultLabel [
	^ 'Female'
]
