Class {
	#name : #LcsGlobalCollectionReferenceSlotDefinitionBuilderTest,
	#superclass : #LcsCodeBuilderStepTest,
	#category : #'Lcs-SlotToolsTests-Tests'
}

{ #category : #tests }
LcsGlobalCollectionReferenceSlotDefinitionBuilderTest >> testCreation [
	<TODO: 'need to add test for creation of slot definition method'>
	self assert: LcsGlobalCollectionReferenceDefinitionSlotBuilder slotDefinitionClass equals: LcsGlobalCollectionReferenceSlot
]
