Class {
	#name : 'LcsLocalCollectionReferenceSlotBuilderTest',
	#superclass : 'LcsCodeBuilderStepTest',
	#category : 'Lcs-SlotToolsTests-Tests',
	#package : 'Lcs-SlotToolsTests',
	#tag : 'Tests'
}

{ #category : 'tests' }
LcsLocalCollectionReferenceSlotBuilderTest >> testCreation [
	<TODO: 'need to add test for creation of slot definition method'>
	self assert: LcsLocalCollectionReferenceSlotBuilder slotClass equals: LcsLocalCollectionReferenceSlot.
]
