Class {
	#name : 'LcsSingletonValueObjectsGlobalCollectionSlotBuilderTest',
	#superclass : 'LcsCodeBuilderStepTest',
	#category : 'Lcs-SlotToolsTests-Examples',
	#package : 'Lcs-SlotToolsTests',
	#tag : 'Examples'
}

{ #category : 'tests' }
LcsSingletonValueObjectsGlobalCollectionSlotBuilderTest >> testCreation [
	<TODO: 'need to add test for creation of slot definition method'>
	self assert: LcsSingletonValueObjectsGlobalCollectionSlotBuilder slotClass equals: LcsSingletonValueObjectsGlobalCollectionSlot.
]
