Class {
	#name : #LcsSingletonValueObjectsGlobalCollectionSlotBuilderTest,
	#superclass : #LcsCodeBuilderStepTest,
	#category : #'Lcs-SlotToolsTests-Tests'
}

{ #category : #tests }
LcsSingletonValueObjectsGlobalCollectionSlotBuilderTest >> testCreation [
	<TODO: 'need to add test for creation of slot definition method'>
	self assert: LcsSingletonValueObjectsGlobalCollectionSlotBuilder slotDefinitionClass equals: LcsSingletonValueObjectsGlobalCollectionSlot.
]
